	FROM oven/bun:1
	WORKDIR /usr/src/app

	ARG DATABASE_URL
	COPY ./packages ./packages
	COPY  ./package.json ./package.json
	COPY ./bun.lock ./bun.lock
	COPY ./turbo.json ./turbo.json
	COPY ./apps/web ./apps/web
	RUN bun install

	RUN bun run db:generate
	RUN  DATABASE_URL=${DATABASE_URL} bun run build
	COPY . .
	EXPOSE 3000
	CMD ["bun","run","start:web"] 